# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('march_madness', '0006_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brackets',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tiebreaker', models.IntegerField()),
                ('game1', models.IntegerField()),
                ('game2', models.IntegerField()),
                ('game3', models.IntegerField()),
                ('game4', models.IntegerField()),
                ('game5', models.IntegerField()),
                ('game6', models.IntegerField()),
                ('game7', models.IntegerField()),
                ('game8', models.IntegerField()),
                ('game9', models.IntegerField()),
                ('game10', models.IntegerField()),
                ('game11', models.IntegerField()),
                ('game12', models.IntegerField()),
                ('game13', models.IntegerField()),
                ('game14', models.IntegerField()),
                ('game15', models.IntegerField()),
                ('game16', models.IntegerField()),
                ('game17', models.IntegerField()),
                ('game18', models.IntegerField()),
                ('game19', models.IntegerField()),
                ('game20', models.IntegerField()),
                ('game21', models.IntegerField()),
                ('game22', models.IntegerField()),
                ('game23', models.IntegerField()),
                ('game24', models.IntegerField()),
                ('game25', models.IntegerField()),
                ('game26', models.IntegerField()),
                ('game27', models.IntegerField()),
                ('game28', models.IntegerField()),
                ('game29', models.IntegerField()),
                ('game30', models.IntegerField()),
                ('game31', models.IntegerField()),
                ('game32', models.IntegerField()),
                ('game33', models.IntegerField()),
                ('game34', models.IntegerField()),
                ('game35', models.IntegerField()),
                ('game36', models.IntegerField()),
                ('game37', models.IntegerField()),
                ('game38', models.IntegerField()),
                ('game39', models.IntegerField()),
                ('game40', models.IntegerField()),
                ('game41', models.IntegerField()),
                ('game42', models.IntegerField()),
                ('game43', models.IntegerField()),
                ('game44', models.IntegerField()),
                ('game45', models.IntegerField()),
                ('game46', models.IntegerField()),
                ('game47', models.IntegerField()),
                ('game48', models.IntegerField()),
                ('game49', models.IntegerField()),
                ('game50', models.IntegerField()),
                ('game51', models.IntegerField()),
                ('game52', models.IntegerField()),
                ('game53', models.IntegerField()),
                ('game54', models.IntegerField()),
                ('game55', models.IntegerField()),
                ('game56', models.IntegerField()),
                ('game57', models.IntegerField()),
                ('game58', models.IntegerField()),
                ('game59', models.IntegerField()),
                ('game60', models.IntegerField()),
                ('game61', models.IntegerField()),
                ('game62', models.IntegerField()),
                ('game63', models.IntegerField()),
                ('game64', models.IntegerField()),
                ('game65', models.IntegerField()),
                ('game66', models.IntegerField()),
                ('game67', models.IntegerField()),
                ('game68', models.IntegerField()),
                ('game69', models.IntegerField()),
                ('submission_time', models.DateTimeField()),
                ('user_id', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
    ]
