from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
class Regions(models.Model):
    region_name = models.CharField(max_length=30)

class Rounds(models.Model):
    round_name = models.CharField(max_length=30)

class Teams(models.Model):
    team_seed = models.IntegerField()
    team_name = models.CharField(max_length=30)
    team_region = models.ForeignKey(Regions)
    picks_to_win = models.IntegerField()

class Games(models.Model):
    hteam = models.IntegerField()
    vteam = models.IntegerField()
    game_region = models.ForeignKey(Regions)
    game_round = models.ForeignKey(Rounds)
    win_game_id = models.IntegerField()
    win_home = models.IntegerField()
    game_winner = models.IntegerField()
    hteam_from = models.IntegerField()
    vteam_from = models.IntegerField()

class Blog(models.Model):
    title = models.CharField(max_length=30)
    subtitle = models.CharField(max_length=30)
    content = models.TextField()
    timestamp = models.DateTimeField()

class Brackets(models.Model):
    best = models.IntegerField(default=0)
    total_score = models.IntegerField(default=0)
    rank = models.IntegerField(default=1)
    tiebreaker = models.IntegerField()
    game1 =  models.IntegerField()
    game2 =  models.IntegerField()
    game3 =  models.IntegerField()
    game4 =  models.IntegerField()
    game5 =  models.IntegerField()
    game6 =  models.IntegerField()
    game7 =  models.IntegerField()
    game8 =  models.IntegerField()
    game9 =  models.IntegerField()
    game10 =  models.IntegerField()
    game11 =  models.IntegerField()
    game12 =  models.IntegerField()
    game13 =  models.IntegerField()
    game14 =  models.IntegerField()
    game15 =  models.IntegerField()
    game16 =  models.IntegerField()
    game17 =  models.IntegerField()
    game18 =  models.IntegerField()
    game19 =  models.IntegerField()
    game20 =  models.IntegerField()
    game21 =  models.IntegerField()
    game22 =  models.IntegerField()
    game23 =  models.IntegerField()
    game24 =  models.IntegerField()
    game25 =  models.IntegerField()
    game26 =  models.IntegerField()
    game27 =  models.IntegerField()
    game28 =  models.IntegerField()
    game29 =  models.IntegerField()
    game30 =  models.IntegerField()
    game31 =  models.IntegerField()
    game32 =  models.IntegerField()
    game33 =  models.IntegerField()
    game34 =  models.IntegerField()
    game35 =  models.IntegerField()
    game36 =  models.IntegerField()
    game37 =  models.IntegerField()
    game38 =  models.IntegerField()
    game39 =  models.IntegerField()
    game40 =  models.IntegerField()
    game41 =  models.IntegerField()
    game42 =  models.IntegerField()
    game43 =  models.IntegerField()
    game44 =  models.IntegerField()
    game45 =  models.IntegerField()
    game46 =  models.IntegerField()
    game47 =  models.IntegerField()
    game48 =  models.IntegerField()
    game49 =  models.IntegerField()
    game50 =  models.IntegerField()
    game51 =  models.IntegerField()
    game52 =  models.IntegerField()
    game53 =  models.IntegerField()
    game54 =  models.IntegerField()
    game55 =  models.IntegerField()
    game56 =  models.IntegerField()
    game57 =  models.IntegerField()
    game58 =  models.IntegerField()
    game59 =  models.IntegerField()
    game60 =  models.IntegerField()
    game61 =  models.IntegerField()
    game62 =  models.IntegerField()
    game63 =  models.IntegerField()
    game64 =  models.IntegerField()
    game65 =  models.IntegerField()
    game66 =  models.IntegerField()
    game67 =  models.IntegerField()
    name = models.CharField(max_length = 45)
    submission_time = models.DateTimeField(auto_now_add=True, blank=False)
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL)

class SmackTalk(models.Model):
    #Need to figure out how to tie admin in with model
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL)
    submission_time = models.DateTimeField(auto_now_add=True, blank=False)
    smack = models.CharField(max_length=300)

class ScoringValues(models.Model):
    last_scored = models.DateTimeField(blank=False)
    seed = models.IntegerField() 
    r1 = models.IntegerField()
    r2 = models.IntegerField()
    r3 = models.IntegerField()
    r4 = models.IntegerField()
    r5 = models.IntegerField()
    r6 = models.IntegerField()
    r7 = models.IntegerField()

class Rules(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    submission = models.DateTimeField(blank=False)

class Site(models.Model):
    name = models.CharField(max_length=30)
    sweet_16 = models.BooleanField() 
    bracket_setup = models.BooleanField()
